apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ojqq1nslz-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-409fa429d5.ljd4.p3.openshiftapps.com/rhtap/rhtap-qe:9d14a03ed50f3cf70f916cea0e19347a5cd792db@sha256:379919e4724ffe9a1fb16b2a78ef386323c534f5003b210e43fc77f26b1eb024
          name: container-image
